#!/usr/bin/env python3
"""Scope a stylesheet to one container: every selector gets the scope prefixed.

Used for nur258-module-06-diabetes.html, whose page is Codex's light study
layout (assets/module06/) but which keeps the site's generated module sections
(mind map, decks, lectures, infographics, Visual references, Active Learning
Template) inside <section id="site-extras">. Those sections are styled by
nur258-module-base.css, absn-adhd-enhanced.css and nur258-module-overrides.css;
loaded unscoped they would repaint Codex's whole page dark.

    python3 tools/scope-css.py '#site-extras' OUT.css IN1.css [IN2.css ...]

:root, html and body become the scope itself, so the site's dark background
and type settle on the container. @media/@supports blocks are scoped inside;
@keyframes, @font-face and @import pass through untouched.
"""
import re, sys

def split_top(s, sep=','):
    out, depth, cur = [], 0, ''
    for ch in s:
        if ch in '([': depth += 1
        elif ch in ')]': depth -= 1
        if ch == sep and depth == 0:
            out.append(cur); cur = ''
        else:
            cur += ch
    out.append(cur)
    return out

def scope_sel(sel, scope):
    s = sel.strip()
    if not s: return s
    m = re.match(r'^(:root|html|body)(?![\w-])', s)
    if m:
        rest = s[m.end():]
        rest = re.sub(r'^\s*(body)(?![\w-])', '', rest)   # "html body x"
        return scope + rest
    return scope + ' ' + s

def scope_css(css, scope):
    css = re.sub(r'/\*.*?\*/', '', css, flags=re.S)
    out, i, n = [], 0, len(css)
    while i < n:
        j = css.find('{', i)
        if j < 0:
            break
        head = css[i:j].strip()
        # find matching close brace
        depth, k = 1, j + 1
        while k < n and depth:
            if css[k] == '{': depth += 1
            elif css[k] == '}': depth -= 1
            k += 1
        body = css[j+1:k-1]
        if head.startswith('@'):
            if re.match(r'@(media|supports|layer|container)', head):
                out.append(head + '{' + scope_css(body, scope) + '}')
            else:
                out.append(head + '{' + body + '}')
        else:
            sels = ','.join(scope_sel(x, scope) for x in split_top(head))
            out.append(sels + '{' + body + '}')
        i = k
    return '\n'.join(out)

if __name__ == '__main__':
    scope, outp, ins = sys.argv[1], sys.argv[2], sys.argv[3:]
    parts = ['/* Generated by tools/scope-css.py from %s - do not hand-edit. */' % ', '.join(ins)]
    for p in ins:
        parts.append(scope_css(open(p, encoding='utf-8').read(), scope))
    open(outp, 'w', encoding='utf-8').write('\n'.join(parts) + '\n')
    print(outp, sum(len(x) for x in parts), 'bytes')
